---
global:
  application: ebisu
  namespace: production

  image:
    repository: "nexus.sigame.com.br"
    pullPolicy: Always
    pullSecret: nexus-v3

  labels:  
    mongo: true
    oracle: true
    postgres: false
    redis: true
    sqlserver: false
    external: true
    priority: 5

  serviceaccount:
    enabled: false
    annotations: []

  configMap:
    enabled: false
    data: {}

  revisionHistoryLimit: 4

  annotations:
    sidecar.istio.io/inject: "true"
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

  nameOverride: ""
  fullnameOverride: ""

  volumes:
    enabled: false
    name:
    hostPath:

  nodeAffinity:
    bff: true

certificate:
  enabled: false
  commonName: "ebisu"
  issuer:
    name: letsencrypt
  dnsNames:
    - ebisu.ligainvest.com.br

restartPolicy: Always

deployment:
  - name: ebisu
    enabled: true
    containers: 
    - name: ebisu
      imagename: null
      tag: 1.0.18
      containerPorts: 8000

      probes:
        enabled: false
      
      env:
        ORACLE_BASE_USER: UBISUDB001
        ORACLE_BASE_PASSWORD: MFhyfjewqjhd3432Vajo
        ORACLE_BASE_DSN: 172.20.16.249
        ORACLE_BASE_PORT: 1521
        ORACLE_BASE_SERVICE_US: OPDBSINA.SUBDBEXACLIPRIV.VCNDB.ORACLEVCN.COM
        ORACLE_BASE_SERVICE_BR: OPDBSINA.SUBDBEXACLIPRIV.VCNDB.ORACLEVCN.COM
        ORACLE_POSITION_USER: UBISUDB001
        ORACLE_POSITION_PASSWORD: MFhyfjewqjhd3432Vajo
        ORACLE_POSITION_DSN: 172.20.16.249
        ORACLE_POSITION_PORT: 1521
        ORACLE_POSITION_SERVICE: OPDBSINA.SUBDBEXACLIPRIV.VCNDB.ORACLEVCN.COM
        MONGO_CONNECTION_URL: mongodb://ebisu:LjhTYpqeb1nkcP8reiyhxy@172.20.28.239:27017,172.20.28.238:27017,172.20.28.76:27017,172.30.18.149:27017/?authSource=admin&replicaSet=rslionx&readPreference=secondary
        MONGODB_DATABASE_NAME: lionx
        MONGODB_USER_COLLECTION: users
        MONGODB_JWT_COLLECTION: jwts
        MONGO_DATABASE_POSEIDON: poseidon
        MONGO_COLLECTION_IZANAMI: izanami
        MONGODB_SNAPSHOT_DATABASE: ebisu
        MONGODB_SNAPSHOT_COLLECTION: exchange_user_snapshot
        DW_AUTHENTICATION_URL: https://bo-api.drivewealth.net/back-office/auth
        DW_BALANCE_URL: https://bo-api.drivewealth.net/back-office/accounts/{}/summary/money
        DW_GET_ALL_TRANSACTIONS_URL: https://bo-api.drivewealth.net/back-office/accounts/{}/transactions
        DW_POSITIONS_URL: https://bo-api.drivewealth.net/back-office/accounts/{}/summary/positions
        FUNDING_AND_WITHDRAWAL_REDIS_HOST_URL: redis://ebisu:FAShjuy9767gdashbjDGHJA@redis.ligainvest.com.br:6379
        FUNDING_AND_WITHDRAWAL_REDIS_CACHE_DB: 2
        AWS_ACCESS_KEY_ID: AKIATZVFXI252UPABZH7
        AWS_SECRET_ACCESS_KEY: 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
        REGION_NAME: sa-east-1
        AWS_FILE_BUCKET_NAME: brokerage-note-and-bank-statement-prod
        JWT_FILE_BUCKET_NAME: heimdall_rsa
        BUCKET_NAME_KEY: auth-gateway-keys-prod
        REDIS_HOST_URL: redis://ebisu:FAShjuy9767gdashbjDGHJA@redis.ligainvest.com.br:6379
        REDIS_CACHE_DB: 1
        BANK_CODE: 469
        MIST_REDIS_URL: redis://mist:FKhu7698y3hrjGDSBD@redis.ligainvest.com.br:6379?db=1
        MIST_AWS_ACCESS_KEY_ID: AKIATZVFXI252UPABZH7
        MIST_AWS_SECRET_ACCESS_KEY: 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
        MIST_REGION_NAME: sa-east-1
        MIST_BUCKET_NAME_KEY: auth-gateway-keys-prod
        MIST_JWT_FILE_BUCKET_NAME: mist_rsa
        MIST_ELECTRONIC_SIGNATURE_FILE_BUCKET_NAME: eletronic-signature-key
        MIST_JWT_REQUIRED_FIELDS: []
        MIST_MONGODB_CONNECTION: mongodb://mist:daskfhfytnaFVDAHb6875@mongo.ligainvest.com.br:27017/?authSource=admin&replicaSet=rslionx&readPreference=secondary
        MIST_ELECTRONIC_SIGNATURE_MAX_ATTEMPTS: 5
        MIST_ENCRYPT_KEY: c_-e_-e_-e_-i_-i
        MIST_FILE_BUCKET_NAME: mist_rsa
        MIST_AUTH_DATABASE_NAME: lionx
        MIST_AUTH_DATABASE_USER_COLLECTION: users
        HEIMDALL_FILE_BUCKET_NAME: heimdall_rsa
        HEIMDALL_AWS_ACCESS_KEY_ID: AKIATZVFXI252UPABZH7
        HEIMDALL_AWS_SECRET_ACCESS_KEY: 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
        HEIMDALL_REGION_NAME: sa-east-1
        HEIMDALL_BUCKET_NAME_KEY: auth-gateway-keys-prod
        HEIMDALL_JWT_REQUIRED_FIELDS: []
        HEIMDALL_REDIS_URL: redis://heimdal:FAhjlkyrliu6789032hgBfda@redis.ligainvest.com.br:6379?db=1
        MEPHO_DW_APP_KEY: 3fc15430-3e2d-486f-8157-4d1b06997944
        MEPHO_DW_USER: bo.liox.api
        MEPHO_DW_PASSWORD: eLNYWa#b8vDG?m!8
        MEPHO_DW_AUTHENTICATION_URL: https://bo-api.drivewealth.net/back-office/auth
        MEPHO_REDIS_HOST: redis://tsukuyomi:LKnfuewqj4321LO@redis.ligainvest.com.br:6379
        MEPHO_REDIS_DB: 1
        BIFROST_KAFKA: cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        TRANSFERS_BETWEEN_SINACOR_AND_DRIVE_WEALTH_TOPIC: ebisu-bifrost.transfers-between-sinacor-and-drive-wealth
        TRANSFERS_BETWEEN_DRIVE_WEALTH_AND_SINACOR_TOPIC: ebisu-bifrost.transfers-between-drive-wealth-and-sinacor
        TRANSFERS_BETWEEN_SINACOR_AND_SINACOR: ebisu-bifrost.transfers-between-sinacor-and-sinacor
        TRANSFERS_BETWEEN_SINACOR_AND_EXTERNAL_BANK: ebisu-bifrost.transfers-between-sinacor-and-external-bank
        ETRIA_LOG_LEVEL: DEBUG
        ROOT_LOG_LEVEL: INFO
        PERSEPHONE_KAFKA_BROKERS: cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        PERSEPHONE_TOPIC_CLIENT_BANK_ACCOUNT: ebisu-persephone.client.bank_account
        FLOKI_SINACOR_BASE_IP: 172.20.35.213:25149
        FLOKI_SINACOR_AUTHENTICATION_ROUTE: infra/api/v1/oauth/token
        FLOKI_SINACOR_CLIENT_ID: 1B5FEA46423D56C0EECD0CEB.SINACOR
        FLOKI_SINACOR_CLIENT_SECRET: AIcWHzXQTXeDPh+QNDMlliM/MPDZzGvG5qBeH1UnG91eo+RhppioUyiMjT5GRDt1XRKPa7AFtbV4yvWtEEGEJKBHRBI96EIwGZTdhjBASho=
        FLOKI_SINACOR_COMPANY_ID: 7029
        FLOKI_REDIS_HOST_URL: redis://bifrost:LnbjkeAopduty854tfsv@redis.ligainvest.com.br:6379?db=1
        FLOKI_REDIS_TOKEN_KEY: access_token_of_floki_to_sinacor
        FLOKI_CLIENT_LOCK_MANAGER_REDIS_URLS: [ "redis://:wkhJ8C2WQhG502Nn@keydb-redlock-1:6379?db=0","redis://:wkhJ8C2WQhG502Nn@keydb-redlock-2:6379?db=0","redis://:wkhJ8C2WQhG502Nn@keydb-redlock-3:6379?db=0","redis://:wkhJ8C2WQhG502Nn@keydb-redlock-4:6379?db=0","redis://:wkhJ8C2WQhG502Nn@keydb-redlock-5:6379?db=0"]
        FLOKI_CLIENT_AUTHENTICATION_RETRY_COUNT: 100
        FLOKI_CLIENT_AUTHENTICATION_RETRY_DELAY_MIN: 0.5
        FLOKI_CLIENT_AUTHENTICATION_RETRY_DELAY_MAX: 0.7
        FLOKI_CLIENT_AUTHENTICATION_LOCK_MANAGER_TIMEOUT: 5
        FLOKI_CLIENT_AUTHENTICATION_LOCK_MANAGER_IDENTIFIER: sinacor_authentication_bifrost
        TRANSFER_WINDOW_START: 11:00:00
        TRANSFER_WINDOW_END: 19:30:00
        PAID_EARNINGS_URL: http://172.20.35.213:25149/custodia/api/EventosCorporativos/Proventos/Pagos
        PROVISIONED_EARNINGS_URL: http://172.20.35.213:25149/custodia/api/EventosCorporativos/Proventos/Provisionados

      
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 700m
          memory: 784Mi
      
      hpa:
        enabled: true
        minReplicas: 1
        maxReplicas: 5
        metrics:
          cpu: 80
          memory: 80

      service:
        metaname: ebisu-service
        enabled: true
        name: http
        protocol: TCP
        annotations: []

      ingress:
        enabled: true
        rewriteURI: /

        cors:
          enabled: false
          allowCredentials: true
          allowOrigins:
          - regex: .
          allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
          allowHeaders:
          - x-thebes-answer