from enum import Enum


class EarningsTypes(Enum):
    DIVIDEND = 10
    CAPITAL_REFUND = 11
    CASH_BONUS = 12
    INTEREST_ON_EQUITY = 13
    YIELD = 14
    FEES = 16
    AMORTIZATION = 17
    AWARD = 18
    BONUS_ON_ASSETS = 20
    REFUND_OF_CAPITAL_IN_SHARES = 21
    CAPITAL_REFUND_WITH_REDUCTION_OF_THE_NUMBER_OF_SHARES = 22
    UNFOLDING = 30
    GROUPING = 40
    UNDERWRITING = 50
    SUBSCRIPTION_PRIORITY = 51
    SUBSCRIPTION_EXERCISE = 52
    SUBSCRIPTION_WITH_WAIVER_OF_PREEMPTIVE_RIGHT = 53
    INCORPORATION = 60
    FUSION = 70
    SPIN_WITH_CAPITAL_REDUCTION = 80
    SPIN_WITH_CAPITAL_AND_QUANTITY_REDUCTION = 81
    UPDATE = 90
    CONVERSION_INTO_ASSETS = 95
    DISSENT = 96
    TOTAL_REDEMPTION_VARIABLE_INCOME = 97
    NET_INCOME = 98
    SUBSCRIPTION_REMAINING = 99
    FIXED_INCOME_PARTIAL_REDEMPTION = 93
    RESTATEMENT = 19
    NOT_IDENTIFIED_ARREST_REGISTRATION_A = 72
    TOTAL_FIXED_INCOME_REDEMPTION = 94
    NOT_IDENTIFIED_ARREST_REGISTRATION_B = 75
    CANCELLATION_OF_FRACTIONS = 71
    DONATION_OF_FRACTIONS = 73
    ADMINISTRATION_OF_FRACTIONS = 74
    SALE_OF_FRACTIONS = 76
    EVENT_WITH_MULTIPLE_REQUIREMENTS_AND_RESULTS = 91
    RETRACTION = 92
