from enum import Enum


class EarningsTypes(Enum):
    DEPOSIT = "LC01"
    WITHDRAWAL = "LC02"
    TRANSFER_OF_SHARES_AND_RIGHTS = "LC03"
    SETTLEMENT_PURCHASES_OR_SALES = "LC04"
    SHARE_GROUP = "LC05"
    SHARE_DECISION = "LC06"
    ISIN_CODE_UPDATE = "LC07"
    DIVIDENDS_AND_OTHER_CASH_INCOME = "LC09"
    BONUS_AND_RIGHTS_RIGHTS = "LC10"
    SUBSCRIPTION_RIGHT = "LC11"
    SUBSCRIPTION_RECEIPTS = "LC12"
    MERGER_OF_SHARES = "LC14"
    VOLUNTEER_EVENTS = "LC15"
    FRACTION_TREATMENT = "LC16"
    FINANCIAL_LCTO_IN_FRACTION_TREATMENT = "LC17"
    PROVISIONED_SUBSCRIPTION_RIGHTS = "LC18"
    UPDATE_OF_BALANCES_COM = "LC19"
    EX_BALANCE_UPDATE = "LC20"
    FRACTION_TREATMENT_FOR_CDS = "LC21"
