# Standards
from enum import Enum


class TIF(Enum):
    DAY = "DAY"
    GOOD_TILL_CANCEL = "GOOD_TILL_CANCEL"
    AT_THE_OPENING = "AT_THE_OPENING"
    IMMEDIATE_OR_CANCEL = "IMMEDIATE_OR_CANCEL"
    FILL_OR_KILL = "FILL_OR_KILL"
    GOOD_TILL_CROSSING = "GOOD_TILL_CROSSING"
    GOOD_TILL_DATE = "GOOD_TILL_DATE"
    AT_THE_CLOSE = "AT_THE_CLOSE"
    GOOD_THROUGH_CROSSING = "GOOD_THROUGH_CROSSING"
    AT_CROSSING = "AT_CROSSING"
    GOOD_FOR_AUCTION = "GOOD_FOR_AUCTION"
