# Standards
from enum import IntEnum


class InternalCode(IntEnum):
    SUCCESS = 0
    INVALID_PARAMS = 10
    INVALID_SIGNATURE_ELECTRONIC = 11
    JWT_INVALID = 30
    UNAUTHORIZED = 40
    NOT_IMPLEMENTED = 90
    DATA_VALIDATION_ERROR = 97
    DATA_ALREADY_EXISTS = 98
    DATA_NOT_FOUND = 99
    INTERNAL_SERVER_ERROR = 100
    DROPPED_TOKEN = 200
    EXPIRED_TOKEN = 201
    INSUFFICIENT_FUNDS = 202
    ERROR_IN_CARONTE = 300
    ERROR_IN_HALBERD = 400
    ERROR_IN_BIFROST_CLIENT = 500
    OUTSIDE_THE_OPERATION_WINDOW = 600
    INVALID_BANK_CODE = 700
    ERROR_IN_US_PARTNER = 800

    def __repr__(self):
        return self.value
