from enum import Enum


class PersephoneQueue(Enum):
    REGISTER_BANK_ACCOUNT = 0
    UPDATE_BANK_ACCOUNT = 1
    DELETE_BANK_ACCOUNT = 2
    CASH_FLOW_WITHDRAWAL_TO_EXTERNAL_BANK = 3
    EXCHANGE_PROPOSAL_SIMULATION = 4
