# Standards
from enum import Enum


class OrderStatus(Enum):
    NEW = "NEW"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    DONE_FOR_DAY = "DONE_FOR_DAY"
    CANCELED = "CANCELED"
    REPLACED = "REPLACED"
    PENDING_CANCEL = "PENDING_CANCEL"
    STOPPED = "STOPPED"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"
    PENDING_NEW = "PENDING_NEW"
    CALCULATED = "CALCULATED"
    EXPIRED = "EXPIRED"
    ACCEPTED_FOR_BIDDING = "ACCEPTED_FOR_BIDDING"
    PENDING_REPLACE = "PENDING_REPLACE"
    PREVIOUS_FINAL_STATE = "PREVIOUS_FINAL_STATE"
    FORWARDED = "FORWARDED"
    DELAYED = "DELAYED"
    TIMEOUT = "TIMEOUT"
